title: Capsicum
description: ðŸ«‘ Retrofit a wired doorbell to add WiFi and make it connected ðŸ””
url: "https://hutscape.com/capsicum"
parent: "https://hutscape.com"
markdown: kramdown
permalink: /:title
youtube: https://www.youtube.com/user/@sayanee/videos
github:
  repository_url: https://github.com/hutscape/capsicum
  raw_content_url: https://raw.githubusercontent.com/hutscape/capsicum/master
exclude: [
  "datasheets",
  "Gemfile",
  "Gemfile.lock",
  "contributing.md",
  "*Makefile",
  "readme.md",
  "scripts",
  "firmware",
  "*.h",
  "*.ino",
  "*.bin",
  "*.elf",
  "*.map"
  ]
include: ["_data"]
collections:
  code:
    output: true
    permalink: /code/:name

project:
  power: 16340
  wireless: WiFi
  mcu: ESP32-C3
  status: ongoing
  started: Oct 2023
