title: Capsicum
description: ðŸ«‘ Retrofit a wired doorbell to add WiFi and make it connected ðŸ””
url: "https://hutscape.com/capsicum"
parent: "https://hutscape.com"
markdown: kramdown
permalink: /:title
youtube: https://youtube.com/@sayanee
paypal: https://www.paypal.com/ncp/payment/4JU23HRF65P66
github:
  repository_url: https://github.com/hutscape/capsicum
  raw_content_url: https://github.com/hutscape/capsicum/blob/main
exclude: [
  "datasheets",
  "Gemfile",
  "Gemfile.lock",
  "contributing.md",
  "*Makefile",
  "readme.md",
  "scripts",
  "firmware",
  "*.h",
  "*.ino",
  "*.bin",
  "*.elf",
  "*.map",
  "*.kicad*",
  "pcb/fp-*",
  "pcb/sym-lib-table",
  "pcb/library",
  "*.FCStd",
  "*.stl",
  "*.FCBak",
  "*-backups",
  "references"
  ]
include: ["_data"]
collections:
  code:
    output: true
    permalink: /code/:name

project:
  power: 16340
  wireless: WiFi
  mcu: ESP32-C3
  status: ongoing
  started: Oct 2023
